
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://101.34.253.64:3306/graduation_lhj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai"
    username: root
    password: lhjlhj
#  redis:
#    host: 127.0.0.1
#    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: graduation_lhj

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.xxxx.server.pojo
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

#logstash:
#  address: 0.0.0.0:5044
#ESHost: 127.0.0.1:9200
#debug: false